version: '3.5'

services:
  db-bumdes:
    container_name: "db-bumdes"
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: bumdes
    networks:
      - bumdes-network
  api:
    build: .
    restart: always
    container_name: "api-bumdes"
    ports:
      - '8081:8080'
    depends_on:
      - db-bumdes
    networks:
      - bumdes-network
    environment:
      - TZ=Asia/Jakarta

networks:
  bumdes-network:
    external: false